#!/usr/bin/python3

import sys

from pathlib import Path

# if called from git source, add parent dir to python path
if Path(__file__).parent.name == 'scripts':
    sys.path.insert(0, str(Path(__file__).parent.parent))

from sftools.argparse import SFObjectArgumentParser


def main():
    parser = SFObjectArgumentParser(default_fields=['CaseNumber'])

    cases_group = parser.add_mutually_exclusive_group()
    cases_group.add_argument('-n', '--casenumber',
                             help='Case number (or Case ID)')
    cases_group.add_argument('-C', '--comment',
                             help='Case comment contains this text')
    cases_group.add_argument('-m', '--mycases', action='store_true',
                             help='Cases owned by me (case owner or escalation owner)')
    cases_group.add_argument('-o', '--owner',
                             help='Cases owner by owner (name or ID)')

    opts = parser.parse_args()
    sf = opts.functions.SF()

    cases = []
    if opts.casenumber:
        cases = [sf.Case(opts.casenumber)]
    elif opts.comment:
        cases = sf.CaseComment.contains(opts.comment, **opts.query_kwargs)
    elif opts.mycases:
        cases = sf.me.cases(**opts.query_kwargs)
    elif opts.owner:
        cases = sf.User(opts.owner).cases(**opts.query_kwargs)

    opts.functions.dumpfields(cases)


if __name__ == "__main__":
    main()
