#!/usr/bin/python3
#
# Copyright 2022 Dan Streetman <ddstreet@ieee.org>

import sys

from pathlib import Path

# if called from git source, add parent dir to python path
if Path(__file__).parent.name == 'scripts':
    sys.path.insert(0, str(Path(__file__).parent.parent))

from sftools.argparse import SFArgumentParser


def main():
    parser = SFArgumentParser()

    lazy = parser.add_mutually_exclusive_group()
    lazy.add_argument('--lazy-fields', action='store_true',
                      help='Load object fields lazily (default, except in shell mode)')
    lazy.add_argument('--preload-fields', action='store_true',
                      help='Preload all object fields (default only in shell mode)')

    action = parser.action_group
    action.add_argument('-o', '--oauth', action='store_true',
                        help='Request new OAuth token')
    action.add_argument('--oauth-refresh', action='store_true',
                        help='Refresh existing OAuth token')
    action.add_argument('-e', '--evaluate',
                        help='Evaluate and print result (e.g. "-e sf.Case(123456).AccountId")')

    opts = parser.parse_args()

    kwargs = {}
    if opts.lazy_fields:
        kwargs['preload_fields'] = False
    elif opts.preload_fields:
        kwargs['preload_fields'] = True

    sf = parser.sf(opts, **kwargs)

    if opts.oauth:
        sf.request_oauth()
    elif opts.oauth_refresh:
        sf.refresh_oauth()
    elif opts.evaluate:
        print(sf.evaluate(opts.evaluate))
    else:
        if 'preload_fields' not in kwargs:
            sf.preload_fields = True
        try:
            import IPython
            IPython.start_ipython(argv=[], user_ns={'sf': sf})
        except ImportError:
            print('Please install ipython.')


if __name__ == "__main__":
    main()
