#!/usr/bin/python3

import sys

from pathlib import Path

# if called from git source, add parent dir to python path
if Path(__file__).parent.name == 'scripts':
    sys.path.insert(0, str(Path(__file__).parent.parent))

from sftools.argparse import SFObjectArgumentParser
from sftools.soql import WhereUtil


def main():
    parser = SFObjectArgumentParser(default_fields=['Name', 'Username', 'Alias'])

    parser.add_argument('-m', '--me', action='store_true',
                        help='Currently authenticated user')
    parser.add_argument('-e', '--email', action='append',
                        help='User Email')
    parser.add_argument('-u', '--userid', action='append',
                        help='User Id (or Alias)')
    parser.add_argument('-n', '--name',
                        help='User name is or contains this value')

    opts = parser.parse_args()
    sf = opts.function.SF()

    users = []
    if opts.me:
        users.append(sf.me)

    if opts.email:
        for e in opts.email:
            matches = sf.User.query(f"Email = '{e}'",
                                    **opts.query_kwargs)
            if matches:
                users.extend(matches)

    if opts.userid:
        for i in opts.userid:
            user = sf.User(i)
            if user:
                users.append(user)

    if opts.name:
        matches = sf.User.query(WhereUtil.LIKE('Name', opts.name),
                             **opts.query_kwargs)
        if matches:
            users.extend(matches)

    opts.functions.dumpfields(users)


if __name__ == "__main__":
    main()
